version: "3.9"
services:
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:latest
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=10.10.20.248
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=sangatrahasia
    networks:
      zbx_net:
        ipv4_address: 172.19.0.3
  web-nginx:
    container_name: web-nginx
    image: zabbix/zabbix-web-nginx-pgsql:latest
    ports:
      - "80:8080"
    env_file:
      - ./env_vars/.env_web
    networks:
      zbx_net:
        ipv4_address: 172.19.0.6
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent:latest
    ports:
      - "10050:10050"
    env_file:
      - ./env_vars/.env_agent
    privileged: true
    networks:
      zbx_net:
        ipv4_address: 172.19.0.2

networks:
  zbx_net:
   driver: bridge
   ipam:
     driver: default
     config:
     - subnet: 172.19.0.0/24
